### ISSUE TITLE
Couleurs rangs discord

### ISSUE THREAD

**Issue by Mopitio** [Lpu8er/mf-discord#23]
à tester au cas ou pour la lisibilitée.

Noble : #2e46ff
Empereur : #c20000
Gouverneur : #db3700

(pour ceux qui chercheraient un outil pour les codes couelurs ^^ : https://www.hexcolortool.com/#db3700/#424242

**Comment by 4nt3ni0** [comment]
Gouverneur : #FA675E ou #ee4c4c
(plus rose)

**Comment by Lpu8er** [comment]
![image](https://user-images.githubusercontent.com/942233/57982146-a7e86900-7a41-11e9-88e4-846a3c6f3947.png)

zou.
