### ISSUE TITLE
Emotes

### ISSUE THREAD

**Issue by Lpu8er** [Lpu8er/mf-discord#26]

**Comment by 4nt3ni0** [comment]
:edl:
https://i.imgur.com/o5I34y9.png

Source : https://www.minefield.fr/forum/topic/64000-suggestions-en-lien-avec-discord/?do=findComment&comment=520999

![image](https://user-images.githubusercontent.com/942233/57971361-4c5ca380-798d-11e9-9306-ccbd1cadec27.png)

**Comment by 4nt3ni0** [comment]
Emotes :stendel: :newstendel: etc... avec les logos des maps

**Comment by MapperTV** [comment]
[jobs.zip](https://github.com/Lpu8er/mf-web/files/3204638/jobs.zip)

Emotes métiers redimensionnées en 128*128 pour qu'elles ne soient pas floues.

**Comment by EL-Thorgrin** [comment]
Merci pour les correctif killer.
C'est en ligne avec l'état des lieux !
