### ISSUE TITLE
Info sup. commande .me

### ISSUE THREAD

**Issue by EL-Thorgrin** [Lpu8er/mf-discord#27]
Rajouter dnas le .me du bot des infos en plus sur le joueur.
PAs
Grade
Métier
Communautés

**Comment by Lpu8er** [comment]
J'ai du mal à comprendre l'intérêt d'afficher grade, métier et commu. Le mec est au courant non ?
Alors que PA, je vois l'intérêt. Est-ce utile de rajouter des permissions juste pour montrer qu'on peut afficher une info que l'user connaît déjà ?

**Comment by 4nt3ni0** [comment]
- Affichage pseudo 
- Lien vers profil site
- Lien vers suivi monétaire
- Nombre de PA / crédit
