### ISSUE TITLE
.mute

### ISSUE THREAD

**Issue by Mopitio** [Lpu8er/mf-discord#31]
ajouter une possibilitée d'interdire un joueur de parler sur discord pendant un temps donné (en secondes/minutes) en cas de gros spam

**Comment by Lpu8er** [comment]
Déjà en place : 
![image](https://user-images.githubusercontent.com/942233/57981108-98622380-7a33-11e9-8539-9558a826d1b5.png)

Si tu parles de mute écrit, discord ne permet pas ça. Les moyens de contournement sont dégueulasses et à bannir.
