### ISSUE TITLE
Gestion de rôles évènements

### ISSUE THREAD

**Issue by 4nt3ni0** [Lpu8er/mf-discord#67]
**Objectif** : création de rôles spécifiques pour des évènements _(ex : 'Events Guilde')_ qui seraient attribués individuellement par le bot aux joueurs par le biais d'une commande, sur la base du volontariat. Le but est d'avoir des rôles que l'on va pouvoir ping quand on fait un évènement qui y est lié, de façon à ne pas passer par des [at]everyone.  

- Création par nous-même (pas par le bot) d'un rôle X
- Création d'une commande du bot _".role X"_ qui ajoute ou enlève le rôle au joueur qui envoie la commande par MP au bot ou dans le salon #bot 

__Idées bonus éventuelles__ : 
- _Création d'une page modofield pour gérer la commande .role_, qui permettrait d'ajouter à cette commande d'autres rôles que l'on créerait plus tard. Histoire que si dans 3 ans on organise une nouvelle session de Jeux Minefieldiens, on puisse créer un rôle pour l'occasion et l'ajouter dans la liste des rôles ajoutables par la commande sans avoir à update le code du bot. 
Dans cette page, on indiquerait l'id du rôle en question + son alias pour la commande -> .role JM (l'alias) permettrait l'ajout du rôle 'Jeux Minefieldiens'. 
Le .help role devrait idéalement être mis à jour automatiquement pour lister les rôles que l'on peut s'ajouter par la commande .role
- _Ajout dans la page modofield d'annonces Discord via le bot la possibilité de choisir quel rang on souhaite ping_ ([at]everyone / [at]here / [at]Events Guilde / etc.)

**Comment by Lpu8er** [comment]
Done.

La commande pour s'attribuer le rôle est `.iam`. On peut l'utiliser dans un salon où le bot est présent ou en DM avec le bot.
Le pendant de la commande pour s'enlever du rôle est `.iamnot`.
En utilisant la commande vide ou via la commande d'aide, on a l'info de quels rôles peuvent être attribués.

Syntaxe:
`.iam <role>`

Exemple de résultat:
```
.iam vous attribue un rôle parmi ceux disponibles:
.iam guilde : @Événements de la guilde
```

J'ai pris la liberté de créer un rôle pour tester.

Le pendant de la modification est coté Modofield, avec deux changements:
* ajout dans l'écran Discord de base des rôles qu'on peut attribuer. Tous les rôles auxquels le bot a accès y sont. J'ai verrouillé les rôles non-pertinents.
* ajout dans l'écran de ping Discord des rôles auxquels une sous-commande a été attribuée
